#!/bin/bash
tmpdir=$(mktemp -dt "$0.XXXXXXXXXX")
tntfile=${tmpdir}/output.t
#fstfile=output.fst

proiel=../bin/proiel
tnt=tnt
#tnt=hunpos

../bin/proiel convert tnt -V $@ > ${tntfile} || exit 1

tnt-para ${tntfile} && mv -vi ${tmpdir}/output.{lex,123} .

echo
echo "Generated parameter files are output.lex and output.123. Try 'tnt output mycorpus.t' to test."
