language: ruby
rvm:
  - 2.4.10
  - 2.5.9
  - 2.6.8
  - 2.7.4
dist: xenial
os: linux
before_install: gem install bundler -v 2.1.4
script:
  - echo "Rubocop $(bundle exec rubocop --version)"
  - bundle exec rubocop -S -E
